apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dashboard-ui
  template:
    metadata:
      labels:
        app: dashboard-ui
    spec:
      containers:
        - image: pyarelflouzia3737890/pyarel-alpine:0.0.2
          name: dashboard-ui
          ports:
            - containerPort: 80
